### ISSUE TITLE
add imagecodecs dependency

### ISSUE THREAD

**Issue by d-v-b** [thewtex/ngff-zarr#38]
Would there be any objection to adding imagecodecs as a dependency here? I'm asking because I tried this library on some of our tiff files and tifffile failed to load them because of a missing LZW codec. Installing imagecodecs solved the problem. Happy to submit a PR if there's interest.

**Comment by thewtex** [comment]
Hi, yes, good point!

We could add it as an optional dependency here:

https://github.com/thewtex/ngff-zarr/blob/4a154994a85e2d222999bb3e5d67ab96f5060244/pyproject.toml#L61

We do not want imagecodecs to always be a dependency for portability (pyodide, etc.) and leanness.

**Comment by GFleishman** [comment]
How exactly do optional dependencies work? When I `pip install ngff-zarr` then `from ngff_zarr import to_ngff_image, to_multiscales, to_ngff_zarr` I was missing dask-image. Just pip installed it myself and then everything worked. I see it's listed in the optional dependencies in pyproject.toml. So forgive the maybe naive question but if ngff-zarr is a dependency for one of my own tools, how do I ensure downstream users will have the optional-in-general-but-required-for-me dependencies? I guess I could make it an explicit requirement for my own package, but that seems like a work around.

**Comment by thewtex** [comment]
Yes, currently the install command is:

```
pip install "ngff-zarr[dask-image]"
```

And your tool's package can also include the optional dependencies in its package configuration requirements, `ngff-zarr[dask-image]`.

Since a goal is to keep the core of ngff-zarr small, minimal, light, and universally deployable, dependencies for packages that provide anti-aliasing filters in the downsampling Methods are optional dependencies. `dask-image` is light itself, but it has a dependency on `scipy`, which is large. 

In the future, we will have a default anti-aliasing method implemented in a small, universal single package with webassembly that will prevent the need to add any optional dependencies in your tool's package requirements.

**Comment by thewtex** [comment]
Closing via #42 #61
