### ISSUE TITLE
Multiscales bug

### ISSUE THREAD

**Issue by GFleishman** [thewtex/ngff-zarr#40]
Seems like a scale level is being skipped? My expectation for this example is scale levels with sizes 512, 256, 128, and 64. But scale3 is 32. `ome_ngff_zarr.zarr/.zattrs` also shows voxel spacings of: 1, 2, 4, 16 - so consistent with the voxel grid sizes - but not what I thought I would get.

<img width="667" alt="Screen Shot 2023-07-12 at 3 12 09 PM" src="https://github.com/thewtex/ngff-zarr/assets/8507206/d02f4180-13be-45ec-be64-35872e30115a">

**Comment by GFleishman** [comment]
It looks like this line is the culprit:
https://github.com/thewtex/ngff-zarr/blob/10cd1587d8134d6213009f0382976fdae97e9245/ngff_zarr/methods/_support.py#L7

I'm not sure this is the right logic.

It also raises a bigger question for me. The way this is written implies to me that to produce scale level N, we downsample scale level N-1. I'm assuming this because the `result_scale_factors` values here are (supposed to be) relative to the previous scale level. But, isn't it best to always be resampling from the full resolution data? Otherwise you have a series of interpolations composed together which gradually reduces fidelity to the original data.

I also don't think resampling from the full resolution input is any slower than from one scale level up, at least in principle. A linear interpolation is always a weighted average of 8 values for example.

Is this a smoothing thing? I know when you go to progressively lower sampling rates you have to smooth to prevent aliasing. I guess it's much faster to smooth the intermediate scale levels. I don't want to distract from the multiscales calculation bug too much, but I've never built an image pyramid maker like this so I don't know what is best practice. @d-v-b What do you think?

**Comment by d-v-b** [comment]
Based on my experience over in [xarray-multiscale](https://github.com/janeliascicomp/xarray-multiscale), it's *much* faster to use scaleX as the input for scaleX+1, and better for memory use too, *especially* if you are working with chunked data. Imagine the difference in intermediate memory consumption between `downsample_by_2(downsample_by_2(downsample_by_2(data)))` vs `downsample_by_8(data)`

re artifacts: first, I think for any _linear_ smoothing + resampling procedure (e.g., gaussian), you don't accumulate artifacts while iteratively downsampling as long as you avoid intermediate typecasting. (For nonlinear smoothing like the windowed mode this no longer holds)... but more importantly, generally people don't care about the details of the low-res images anyway  (this would change if people routinely used the low-res scale data as input for analysis).

**Comment by GFleishman** [comment]
This package does have nearest neighbor and windowed mode options for downsampling. Personally, I prefer the docstrings for these options to acknowledge the increasing possibility of aliasing or other artifacts for the smaller scale levels. I agree at face value it's bad practice to use the down sampled scale levels for any analysis - but there's plenty of bad practice out there. Best to have a disclaimer for such things. @thewtex Completely up to you of course.

**Comment by thewtex** [comment]
@GFleishman While theoretically, yes, more accurate results will be produced by applying the anti-aliasing filter directly for the downsampling scale desired then sampling. As @d-v-b pointed out, though, the computational expense makes that strategy not feasible in practice. We are then processing a terabyte volume to produce a downsampled volume that is less than a megabyte. Also, the domain of the region to produce an output voxel across these large scales is extremely large, which introduces memory-usage challenges.

I did some research and personal experimentation on this topic (unfortunately I do not have references readily available). It turns out that of the factors:

- The anti-aliasing filter
- Recursive vs direct downsampling
- The interpolation method

for the creation of multi-scale filters, the anti-aliasing filter is, by far, the critical factor (and guassian filtering is the best), and recursive vs direct downsampling or the interpolation method result in negligible differences in the multiscale result.

This is easy to reproduce and examine with your own data. Take a large dataset and use ngff-zarr with scale factors: `[2, 4, 8, 16]` and compare the result to `[16,]`. And compare anti-aliasing filters (`Method`'s) and hack interpolation methods.

@GFleishman yes, you are right we should make the strategy clear in our documentation. We need better documentation in general :-) -- I will get started on our ReadTheDocs.
